<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pages.Reporting.Core\Pages.Reporting.Core.csproj" />
    <ProjectReference Include="..\..\src\Pages.Reporting.Blazor\Pages.Reporting.Blazor.csproj" />
    <ProjectReference Include="..\..\src\Pages.Reporting.Export\Pages.Reporting.Export.csproj" />
    <ProjectReference Include="..\..\src\Pages.Reporting.Designer\Pages.Reporting.Designer.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
